[pytest]

miniversion = 6.0
addopts = -v  --html=reports/report.html
testpaths = ./tests
pythonpath = .

python_files = test_*.py
python_classes = Test*
python_functions = test*

log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S

