[pytest]

addopts = -v  --html=reports/report.html
testpaths = ./tests
pythonpath = .

python_files = test_*.py
python_classes = Test*
python_functions = test*

; this setting can be considered as a global StreamHandler and if set a class parameter in the Base Page Model then every page 
; can use it to print logger in the console, however a FileHandler has to be set separately in the conftest.py 
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S

